package com.example.DentalCoworking.entities;


import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "clinics")
public class Clinic implements Serializable {

    //atributos de la entidad
    /**
     * id autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false,length = 40,name = "name")
    private String name;
    @Column(name = "phone")
    private String phone;
    @Column(nullable = false,unique = true)
    private String email;
    @Column(name = "cabinets_available")
    private int cabinetsAvailable;

    //asociaciones : OneToOne, OneToMany, ManyToOne, ManyToMany
    //obtengo una lista de gabinetes libres.consultaremos siempre desde aqui para sacar los gabinetes libres
    @OneToMany
    private List<Cabinete> cabinete = new ArrayList<>();//la inicializamos vacia para no tener una excepion

    //Gabinetes

    //Reserva


    //constructores

    public Clinic() {
    }

    public Clinic(Long id, String name, String phone, String email, int cabinetsAvailable) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.cabinetsAvailable =cabinetsAvailable;
    }

    //getter y setter
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getname() {
        return name;
    }

    public void setname(String name) {
        this.name = name;
    }

    public String getphone() {
        return phone;
    }

    public void setphone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getNumGabinetes() {
        return cabinetsAvailable;
    }

    public void setNumGabinetes(int numGabinetes) {
        this.cabinetsAvailable = numGabinetes;
    }

    public List<Cabinete> getCabinete() {
        return cabinete;
    }

    public void setCabinete(List<Cabinete> cabinete) {
        this.cabinete = cabinete;
    }

    //toString

    @Override
    public String toString() {
        return "Clinica{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", numGabinetes=" + cabinetsAvailable +
                '}';
    }
}
